<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Sessions', 'doctrine');

/**
 * BaseSessions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $session_id
 * @property string $ip
 * @property timestamp $started_at
 * @property timestamp $expires_at
 * 
 * @method integer   getId()         Returns the current record's "id" value
 * @method integer   getSessionId()  Returns the current record's "session_id" value
 * @method string    getIp()         Returns the current record's "ip" value
 * @method timestamp getStartedAt()  Returns the current record's "started_at" value
 * @method timestamp getExpiresAt()  Returns the current record's "expires_at" value
 * @method Sessions  setId()         Sets the current record's "id" value
 * @method Sessions  setSessionId()  Sets the current record's "session_id" value
 * @method Sessions  setIp()         Sets the current record's "ip" value
 * @method Sessions  setStartedAt()  Sets the current record's "started_at" value
 * @method Sessions  setExpiresAt()  Sets the current record's "expires_at" value
 * 
 * @package    runforever
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSessions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sessions');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('session_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ip', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('started_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('expires_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}