<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RfGearReviews', 'doctrine');

/**
 * BaseRfGearReviews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $product
 * @property string $product_description
 * @property string $review_text
 * @property float $star_rating
 * @property string $published_status
 * 
 * @method integer       get()                    Returns the current record's "id" value
 * @method string        get()                    Returns the current record's "product" value
 * @method string        get()                    Returns the current record's "product_description" value
 * @method string        get()                    Returns the current record's "review_text" value
 * @method float         get()                    Returns the current record's "star_rating" value
 * @method string        get()                    Returns the current record's "published_status" value
 * @method RfGearReviews set()                    Sets the current record's "id" value
 * @method RfGearReviews set()                    Sets the current record's "product" value
 * @method RfGearReviews set()                    Sets the current record's "product_description" value
 * @method RfGearReviews set()                    Sets the current record's "review_text" value
 * @method RfGearReviews set()                    Sets the current record's "star_rating" value
 * @method RfGearReviews set()                    Sets the current record's "published_status" value
 * 
 * @package    runforever
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRfGearReviews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rf_gear_reviews');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('product', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('product_description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('review_text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('star_rating', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('published_status', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}