<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RfSessions', 'doctrine');

/**
 * BaseRfSessions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property string $ip
 * @property integer $uid
 * @property timestamp $started_at
 * @property timestamp $expires_at
 * 
 * @method string     get()           Returns the current record's "id" value
 * @method string     get()           Returns the current record's "ip" value
 * @method integer    get()           Returns the current record's "uid" value
 * @method timestamp  get()           Returns the current record's "started_at" value
 * @method timestamp  get()           Returns the current record's "expires_at" value
 * @method RfSessions set()           Sets the current record's "id" value
 * @method RfSessions set()           Sets the current record's "ip" value
 * @method RfSessions set()           Sets the current record's "uid" value
 * @method RfSessions set()           Sets the current record's "started_at" value
 * @method RfSessions set()           Sets the current record's "expires_at" value
 * 
 * @package    runforever
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRfSessions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rf_sessions');
        $this->hasColumn('id', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('ip', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('uid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('started_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('expires_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}