<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RfBlogPosts', 'doctrine');

/**
 * BaseRfBlogPosts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $pid
 * 
 * @method integer     getId()  Returns the current record's "id" value
 * @method integer     getPid() Returns the current record's "pid" value
 * @method RfBlogPosts setId()  Sets the current record's "id" value
 * @method RfBlogPosts setPid() Sets the current record's "pid" value
 * 
 * @package    runforever
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRfBlogPosts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rf_blog_posts');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('pid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}