<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RfSurveyAnswers', 'doctrine');

/**
 * BaseRfSurveyAnswers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $question_id
 * @property string $ans_text
 * @property integer $uid
 * @property timestamp $created_on
 * @property timestamp $updated_on
 * @property RfSurveyQuestions $RfSurveyQuestions
 * 
 * @method integer           get()                  Returns the current record's "id" value
 * @method integer           get()                  Returns the current record's "question_id" value
 * @method string            get()                  Returns the current record's "ans_text" value
 * @method integer           get()                  Returns the current record's "uid" value
 * @method timestamp         get()                  Returns the current record's "created_on" value
 * @method timestamp         get()                  Returns the current record's "updated_on" value
 * @method RfSurveyQuestions get()                  Returns the current record's "RfSurveyQuestions" value
 * @method RfSurveyAnswers   set()                  Sets the current record's "id" value
 * @method RfSurveyAnswers   set()                  Sets the current record's "question_id" value
 * @method RfSurveyAnswers   set()                  Sets the current record's "ans_text" value
 * @method RfSurveyAnswers   set()                  Sets the current record's "uid" value
 * @method RfSurveyAnswers   set()                  Sets the current record's "created_on" value
 * @method RfSurveyAnswers   set()                  Sets the current record's "updated_on" value
 * @method RfSurveyAnswers   set()                  Sets the current record's "RfSurveyQuestions" value
 * 
 * @package    runforever
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRfSurveyAnswers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rf_survey_answers');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('question_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ans_text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('uid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_on', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_on', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RfSurveyQuestions', array(
             'local' => 'question_id',
             'foreign' => 'id'));
    }
}