<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RfFilms', 'doctrine');

/**
 * BaseRfFilms
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $film_title
 * @property string $film_genre
 * @property string $imdb_link
 * @property string $directed_by
 * @property string $cast
 * @property timestamp $release_date
 * @property float $star_rating
 * 
 * @method integer   get()             Returns the current record's "id" value
 * @method string    get()             Returns the current record's "film_title" value
 * @method string    get()             Returns the current record's "film_genre" value
 * @method string    get()             Returns the current record's "imdb_link" value
 * @method string    get()             Returns the current record's "directed_by" value
 * @method string    get()             Returns the current record's "cast" value
 * @method timestamp get()             Returns the current record's "release_date" value
 * @method float     get()             Returns the current record's "star_rating" value
 * @method RfFilms   set()             Sets the current record's "id" value
 * @method RfFilms   set()             Sets the current record's "film_title" value
 * @method RfFilms   set()             Sets the current record's "film_genre" value
 * @method RfFilms   set()             Sets the current record's "imdb_link" value
 * @method RfFilms   set()             Sets the current record's "directed_by" value
 * @method RfFilms   set()             Sets the current record's "cast" value
 * @method RfFilms   set()             Sets the current record's "release_date" value
 * @method RfFilms   set()             Sets the current record's "star_rating" value
 * 
 * @package    runforever
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRfFilms extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rf_films');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('film_title', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('film_genre', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('imdb_link', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('directed_by', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('cast', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('release_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('star_rating', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}