<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RfEmailQueue', 'doctrine');

/**
 * BaseRfEmailQueue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $subject
 * @property string $body
 * @property string $recipient_email_address
 * @property integer $sent_status
 * @property timestamp $date_sent
 * 
 * @method integer      get()                        Returns the current record's "id" value
 * @method string       get()                        Returns the current record's "subject" value
 * @method string       get()                        Returns the current record's "body" value
 * @method string       get()                        Returns the current record's "recipient_email_address" value
 * @method integer      get()                        Returns the current record's "sent_status" value
 * @method timestamp    get()                        Returns the current record's "date_sent" value
 * @method RfEmailQueue set()                        Sets the current record's "id" value
 * @method RfEmailQueue set()                        Sets the current record's "subject" value
 * @method RfEmailQueue set()                        Sets the current record's "body" value
 * @method RfEmailQueue set()                        Sets the current record's "recipient_email_address" value
 * @method RfEmailQueue set()                        Sets the current record's "sent_status" value
 * @method RfEmailQueue set()                        Sets the current record's "date_sent" value
 * 
 * @package    runforever
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRfEmailQueue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rf_email_queue');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('subject', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('recipient_email_address', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('sent_status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('date_sent', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}