<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RfBlogTerms', 'doctrine');

/**
 * BaseRfBlogTerms
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $term_id
 * 
 * @method integer     getTermId()  Returns the current record's "term_id" value
 * @method RfBlogTerms setTermId()  Sets the current record's "term_id" value
 * 
 * @package    runforever
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRfBlogTerms extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rf_blog_terms');
        $this->hasColumn('term_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}