<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RfSurvey', 'doctrine');

/**
 * BaseRfSurvey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $RfSurveyQuestions
 * 
 * @method integer             get()                  Returns the current record's "id" value
 * @method string              get()                  Returns the current record's "name" value
 * @method Doctrine_Collection get()                  Returns the current record's "RfSurveyQuestions" collection
 * @method RfSurvey            set()                  Sets the current record's "id" value
 * @method RfSurvey            set()                  Sets the current record's "name" value
 * @method RfSurvey            set()                  Sets the current record's "RfSurveyQuestions" collection
 * 
 * @package    runforever
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRfSurvey extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rf_survey');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('RfSurveyQuestions', array(
             'local' => 'id',
             'foreign' => 'survey_id'));
    }
}