<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RfBlogPosts', 'doctrine');

/**
 * BaseRfBlogPosts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $position
 * @property string $title
 * @property string $body
 * @property string $img_src
 * @property timestamp $created_on
 * @property timestamp $updated_on
 * 
 * @method integer     get()           Returns the current record's "id" value
 * @method integer     get()           Returns the current record's "position" value
 * @method string      get()           Returns the current record's "title" value
 * @method string      get()           Returns the current record's "body" value
 * @method string      get()           Returns the current record's "img_src" value
 * @method timestamp   get()           Returns the current record's "created_on" value
 * @method timestamp   get()           Returns the current record's "updated_on" value
 * @method RfBlogPosts set()           Sets the current record's "id" value
 * @method RfBlogPosts set()           Sets the current record's "position" value
 * @method RfBlogPosts set()           Sets the current record's "title" value
 * @method RfBlogPosts set()           Sets the current record's "body" value
 * @method RfBlogPosts set()           Sets the current record's "img_src" value
 * @method RfBlogPosts set()           Sets the current record's "created_on" value
 * @method RfBlogPosts set()           Sets the current record's "updated_on" value
 * 
 * @package    runforever
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRfBlogPosts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rf_blog_posts');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('position', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('img_src', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('created_on', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_on', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}