<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RfBlogTermRelationships', 'doctrine');

/**
 * BaseRfBlogTermRelationships
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $rid
 * 
 * @method integer                 getRid() Returns the current record's "rid" value
 * @method RfBlogTermRelationships setRid() Sets the current record's "rid" value
 * 
 * @package    runforever
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRfBlogTermRelationships extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rf_blog_term_relationships');
        $this->hasColumn('rid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}