<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RunningQuotes', 'doctrine');

/**
 * BaseRunningQuotes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $qid
 * @property string $quote_author
 * @property string $quote_text
 * 
 * @method integer       getQid()          Returns the current record's "qid" value
 * @method string        getQuoteAuthor()  Returns the current record's "quote_author" value
 * @method string        getQuoteText()    Returns the current record's "quote_text" value
 * @method RunningQuotes setQid()          Sets the current record's "qid" value
 * @method RunningQuotes setQuoteAuthor()  Sets the current record's "quote_author" value
 * @method RunningQuotes setQuoteText()    Sets the current record's "quote_text" value
 * 
 * @package    runforever
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRunningQuotes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('running_quotes');
        $this->hasColumn('qid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('quote_author', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('quote_text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}