<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RfSurveyQuestions', 'doctrine');

/**
 * BaseRfSurveyQuestions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $survey_id
 * @property string $question_text
 * @property RfSurvey $RfSurvey
 * @property Doctrine_Collection $RfSurveyAnswers
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method integer             getSurveyId()        Returns the current record's "survey_id" value
 * @method string              getQuestionText()    Returns the current record's "question_text" value
 * @method RfSurvey            getRfSurvey()        Returns the current record's "RfSurvey" value
 * @method Doctrine_Collection getRfSurveyAnswers() Returns the current record's "RfSurveyAnswers" collection
 * @method RfSurveyQuestions   setId()              Sets the current record's "id" value
 * @method RfSurveyQuestions   setSurveyId()        Sets the current record's "survey_id" value
 * @method RfSurveyQuestions   setQuestionText()    Sets the current record's "question_text" value
 * @method RfSurveyQuestions   setRfSurvey()        Sets the current record's "RfSurvey" value
 * @method RfSurveyQuestions   setRfSurveyAnswers() Sets the current record's "RfSurveyAnswers" collection
 * 
 * @package    runforever
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRfSurveyQuestions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rf_survey_questions');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('survey_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('question_text', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RfSurvey', array(
             'local' => 'survey_id',
             'foreign' => 'id'));

        $this->hasMany('RfSurveyAnswers', array(
             'local' => 'id',
             'foreign' => 'question_id'));
    }
}