<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RfBlogTermTaxonomy', 'doctrine');

/**
 * BaseRfBlogTermTaxonomy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * 
 * @method integer            get()   Returns the current record's "id" value
 * @method RfBlogTermTaxonomy set()   Sets the current record's "id" value
 * 
 * @package    runforever
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRfBlogTermTaxonomy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rf_blog_term_taxonomy');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}