<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RfComment', 'doctrine');

/**
 * BaseRfComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $post_id
 * @property string $comment_text
 * @property integer $uid
 * @property date $created
 * 
 * @method integer   get()             Returns the current record's "id" value
 * @method integer   get()             Returns the current record's "post_id" value
 * @method string    get()             Returns the current record's "comment_text" value
 * @method integer   get()             Returns the current record's "uid" value
 * @method date      get()             Returns the current record's "created" value
 * @method RfComment set()             Sets the current record's "id" value
 * @method RfComment set()             Sets the current record's "post_id" value
 * @method RfComment set()             Sets the current record's "comment_text" value
 * @method RfComment set()             Sets the current record's "uid" value
 * @method RfComment set()             Sets the current record's "created" value
 * 
 * @package    runforever
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRfComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rf_comment');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('post_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('comment_text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('uid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}