<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RunningGearReviews', 'doctrine');

/**
 * BaseRunningGearReviews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $rid
 * @property string $review_text
 * 
 * @method integer            getId()          Returns the current record's "id" value
 * @method integer            getRid()         Returns the current record's "rid" value
 * @method string             getReviewText()  Returns the current record's "review_text" value
 * @method RunningGearReviews setId()          Sets the current record's "id" value
 * @method RunningGearReviews setRid()         Sets the current record's "rid" value
 * @method RunningGearReviews setReviewText()  Sets the current record's "review_text" value
 * 
 * @package    runforever
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRunningGearReviews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('running_gear_reviews');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('rid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('review_text', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}