<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RfArticles', 'doctrine');

/**
 * BaseRfArticles
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $aid
 * @property string $title
 * @property string $author
 * @property string $url
 * @property string $img_src
 * @property string $source
 * @property timestamp $date_published
 * 
 * @method integer    getAid()            Returns the current record's "aid" value
 * @method string     getTitle()          Returns the current record's "title" value
 * @method string     getAuthor()         Returns the current record's "author" value
 * @method string     getUrl()            Returns the current record's "url" value
 * @method string     getImgSrc()         Returns the current record's "img_src" value
 * @method string     getSource()         Returns the current record's "source" value
 * @method timestamp  getDatePublished()  Returns the current record's "date_published" value
 * @method RfArticles setAid()            Sets the current record's "aid" value
 * @method RfArticles setTitle()          Sets the current record's "title" value
 * @method RfArticles setAuthor()         Sets the current record's "author" value
 * @method RfArticles setUrl()            Sets the current record's "url" value
 * @method RfArticles setImgSrc()         Sets the current record's "img_src" value
 * @method RfArticles setSource()         Sets the current record's "source" value
 * @method RfArticles setDatePublished()  Sets the current record's "date_published" value
 * 
 * @package    runforever
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRfArticles extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rf_articles');
        $this->hasColumn('aid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('author', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('url', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('img_src', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('source', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('date_published', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}