<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/06/06 23:04:19

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:unix_socket=/var/run/mysqld/mysqld.sock;dbname=run_forever',
  'username' => 'root',
  'password' => 'pro447',
  'name' => 'doctrine',
)),);
