<?php

/**
 * RfArticlesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RfArticlesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RfArticlesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RfArticles');
    }
}