<?php

/**
 * RfBlogTermRelationshipsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RfBlogTermRelationshipsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RfBlogTermRelationshipsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RfBlogTermRelationships');
    }
}