<?php

/**
 * RfCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RfCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RfCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RfComment');
    }
}