<?php

/**
 * RfGearReviewsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RfGearReviewsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RfGearReviewsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RfGearReviews');
    }
}