<?php

/**
 * RfInspirationalMoviesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RfInspirationalMoviesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RfInspirationalMoviesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RfInspirationalMovies');
    }
}