<?php

/**
 * RfPicsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RfPicsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RfPicsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RfPics');
    }
}