<?php

/**
 * RfQuotesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RfQuotesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RfQuotesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RfQuotes');
    }
}