<?php

/**
 * RfRecipesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RfRecipesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RfRecipesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RfRecipes');
    }
}