<?php

/**
 * RfSurveyAnswersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RfSurveyAnswersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RfSurveyAnswersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RfSurveyAnswers');
    }
}