<?php

/**
 * RfSurveyQuestionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RfSurveyQuestionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RfSurveyQuestionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RfSurveyQuestions');
    }
}