<?php

/**
 * RfSurveyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RfSurveyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RfSurveyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RfSurvey');
    }
}