<?php

/**
 * RfUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RfUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RfUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RfUsers');
    }
}