<?php

/**
 * RunningGearReviewsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RunningGearReviewsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RunningGearReviewsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RunningGearReviews');
    }
}