<?php

/**
 * RunningPicsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RunningPicsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RunningPicsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RunningPics');
    }
}