<?php

/**
 * RunningQuotesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RunningQuotesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RunningQuotesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RunningQuotes');
    }
}