generator:
  class: sfDoctrineGenerator
  param:
    model_class:           RfBlogPosts
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          rf_blog_posts
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter: 
        class: false
      form:    ~
      edit:    ~
      new:     ~
