<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/06/06 21:46:31

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=runforever',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
