RunningGearReviews:
  connection: doctrine
  tableName: running_gear_reviews
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    rid:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    review_text:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
RunningPics:
  connection: doctrine
  tableName: running_pics
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    pic_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    img_src:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    img:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
RunningQuotes:
  connection: doctrine
  tableName: running_quotes
  columns:
    qid:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    quote_author:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    quote_text:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Sessions:
  connection: doctrine
  tableName: sessions
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    session_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    ip:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    started_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    expires_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Users:
  connection: doctrine
  tableName: users
  columns:
    uid:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    username:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    userpass:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    ip:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
